### PR TITLE
SickChill update

### PR DESCRIPTION
**Pull request by Mhynlo**
Less rage, more chill
Updated version to reflect update
Update migrates content from sickrage's app for new installs
Changed the port to 6766 (to prevent conflicts)

### CODE REVIEW

**Comment by theskillwithin** [comment]
Does this fix the most recent problem where when i click update it breaks sickrage all the sudden (even tho clicking update has never had problems before)

**Comment by Mhynlo** [comment]
This does address the update issues since it pulls from the correct (SickChill) repo instead of the SickRage repo that got pulled.

**Comment by theskillwithin** [comment]
still waiting on this... if there is problem maybe i can help?

**Comment by Mhynlo** [comment]
The build from this PR works. I do not have access to complete the PR.

The error that came from travis is due to a mis-configuration.

**Comment by horganhoozen** [comment]
I installed the ReadyNAS release for SickChill dated 10-15-2018 and it will not launch correctly. It opens a web page on the new port but it comes up connection refused.

**Comment by miigotu** [comment]
@Mhynlo I never saw this PR, sorry. If you have accepted the team invitation I will give you access to this repo now.

**Pull request merged**
